<?php

namespace App\Enums;

enum BillingCountryType: string
{
    use EnumTrait;

    case AF = 'af';
    case AX = 'ax';
    case AL = 'al';
    case DZ = 'dz';
    case AS = 'as';
    case AD = 'ad';
    case AO = 'ao';
    case AI = 'ai';
    case AQ = 'aq';
    case AG = 'ag';
    case AR = 'ar';
    case AM = 'am';
    case AW = 'aw';
    case AU = 'au';
    case AT = 'at';
    case AZ = 'az';
    case BS = 'bs';
    case BH = 'bh';
    case BD = 'bd';
    case BB = 'bb';
    case BY = 'by';
    case BE = 'be';
    case BZ = 'bz';
    case BJ = 'bj';
    case BM = 'bm';
    case BT = 'bt';
    case BO = 'bo';
    case BA = 'ba';
    case BW = 'bw';
    case BV = 'bv';
    case BR = 'br';
    case IO = 'io';
    case VG = 'vg';
    case BN = 'bn';
    case BG = 'bg';
    case BF = 'bf';
    case BI = 'bi';
    case KH = 'kh';
    case CM = 'cm';
    case CA = 'ca';
    case CV = 'cv';
    case KY = 'ky';
    case CF = 'cf';
    case TD = 'td';
    case CL = 'cl';
    case CN = 'cn';
    case CX = 'cx';
    case CC = 'cc';
    case CO = 'co';
    case KM = 'km';
    case CD = 'cd';
    case CG = 'cg';
    case CK = 'ck';
    case CR = 'cr';
    case CI = 'ci';
    case HR = 'hr';
    case CU = 'cu';
    case CY = 'cy';
    case CZ = 'cz';
    case DK = 'dk';
    case DJ = 'dj';
    case DM = 'dm';
    case DO = 'do';
    case EC = 'ec';
    case EG = 'eg';
    case SV = 'sv';
    case GQ = 'gq';
    case ER = 'er';
    case EE = 'ee';
    case ET = 'et';
    case FO = 'fo';
    case FK = 'fk';
    case FJ = 'fj';
    case FI = 'fi';
    case FR = 'fr';
    case GF = 'gf';
    case PF = 'pf';
    case TF = 'tf';
    case GA = 'ga';
    case GM = 'gm';
    case GE = 'ge';
    case DE = 'de';
    case GH = 'gh';
    case GI = 'gi';
    case GR = 'gr';
    case GL = 'gl';
    case GD = 'gd';
    case GP = 'gp';
    case GU = 'gu';
    case GT = 'gt';
    case GG = 'gg';
    case GN = 'gn';
    case GW = 'gw';
    case GY = 'gy';
    case HT = 'ht';
    case HM = 'hm';
    case VA = 'va';
    case HN = 'hn';
    case HK = 'hk';
    case HU = 'hu';
    case IS = 'is';
    case IN = 'in';
    case ID = 'id';
    case IR = 'ir';
    case IQ = 'iq';
    case IE = 'ie';
    case IM = 'im';
    case IL = 'il';
    case IT = 'it';
    case JM = 'jm';
    case JP = 'jp';
    case JE = 'je';
    case JO = 'jo';
    case KZ = 'kz';
    case KE = 'ke';
    case KI = 'ki';
    case KP = 'kp';
    case KR = 'kr';
    case KW = 'kw';
    case KG = 'kg';
    case LA = 'la';
    case LV = 'lv';
    case LB = 'lb';
    case LS = 'ls';
    case LR = 'lr';
    case LY = 'ly';
    case LI = 'li';
    case LT = 'lt';
    case LU = 'lu';
    case MO = 'mo';
    case MK = 'mk';
    case MG = 'mg';
    case MW = 'mw';
    case MY = 'my';
    case MV = 'mv';
    case ML = 'ml';
    case MT = 'mt';
    case MH = 'mh';
    case MQ = 'mq';
    case MR = 'mr';
    case MU = 'mu';
    case YT = 'yt';
    case MX = 'mx';
    case FM = 'fm';
    case MD = 'md';
    case MC = 'mc';
    case MN = 'mn';
    case ME = 'me';
    case MS = 'ms';
    case MA = 'ma';
    case MZ = 'mz';
    case MM = 'mm';
    case NA = 'na';
    case NR = 'nr';
    case NP = 'np';
    case AN = 'an';
    case NL = 'nl';
    case NC = 'nc';
    case NZ = 'nz';
    case NI = 'ni';
    case NE = 'ne';
    case NG = 'ng';
    case NU = 'nu';
    case NF = 'nf';
    case MP = 'mp';
    case NO = 'no';
    case OM = 'om';
    case PK = 'pk';
    case PW = 'pw';
    case PS = 'ps';
    case PA = 'pa';
    case PG = 'pg';
    case PY = 'py';
    case PE = 'pe';
    case PH = 'ph';
    case PN = 'pn';
    case PL = 'pl';
    case PT = 'pt';
    case PR = 'pr';
    case QA = 'qa';
    case RE = 're';
    case RO = 'ro';
    case RU = 'ru';
    case RW = 'rw';
    case BL = 'bl';
    case SH = 'sh';
    case KN = 'kn';
    case LC = 'lc';
    case MF = 'mf';
    case PM = 'pm';
    case VC = 'vc';
    case WS = 'ws';
    case SM = 'sm';
    case ST = 'st';
    case SA = 'sa';
    case SN = 'sn';
    case RS = 'rs';
    case SC = 'sc';
    case SL = 'sl';
    case SG = 'sg';
    case SK = 'sk';
    case SI = 'si';
    case SB = 'sb';
    case SO = 'so';
    case ZA = 'za';
    case GS = 'gs';
    case ES = 'es';
    case LK = 'lk';
    case SD = 'sd';
    case SR = 'sr';
    case SJ = 'sj';
    case SZ = 'sz';
    case SE = 'se';
    case CH = 'ch';
    case SY = 'sy';
    case TW = 'tw';
    case TJ = 'tj';
    case TZ = 'tz';
    case TH = 'th';
    case TL = 'tl';
    case TG = 'tg';
    case TK = 'tk';
    case TO = 'to';
    case TT = 'tt';
    case TN = 'tn';
    case TR = 'tr';
    case TM = 'tm';
    case TC = 'tc';
    case TV = 'tv';
    case UG = 'ug';
    case UA = 'ua';
    case AE = 'ae';
    case GB = 'gb';
    case US = 'us';
    case UM = 'um';
    case VI = 'vi';
    case UY = 'uy';
    case UZ = 'uz';
    case VU = 'vu';
    case VE = 've';
    case VN = 'vn';
    case WF = 'wf';
    case EH = 'eh';
    case YE = 'ye';
    case ZM = 'zm';
    case ZW = 'zw';

    public function title(): string
    {
        return match ($this) {
            self::AF => 'Afghanistan',
            self::AX => 'Aland Islands',
            self::AL => 'Albania',
            self::DZ => 'Algeria',
            self::AS => 'American Samoa',
            self::AD => 'Andorra',
            self::AO => 'Angola',
            self::AI => 'Anguilla',
            self::AQ => 'Antarctica',
            self::AG => 'Antigua and Barbuda',
            self::AR => 'Argentina',
            self::AM => 'Armenia',
            self::AW => 'Aruba',
            self::AU => 'Australia',
            self::AT => 'Austria',
            self::AZ => 'Azerbaijan',
            self::BS => 'Bahamas the',
            self::BH => 'Bahrain',
            self::BD => 'Bangladesh',
            self::BB => 'Barbados',
            self::BY => 'Belarus',
            self::BE => 'Belgium',
            self::BZ => 'Belize',
            self::BJ => 'Benin',
            self::BM => 'Bermuda',
            self::BT => 'Bhutan',
            self::BO => 'Bolivia',
            self::BA => 'Bosnia and Herzegovina',
            self::BW => 'Botswana',
            self::BV => 'Bouvet Island (Bouvetoya)',
            self::BR => 'Brazil',
            self::IO => 'British Indian Ocean Territory (Chagos Archipelago)',
            self::VG => 'British Virgin Islands',
            self::BN => 'Brunei Darussalam',
            self::BG => 'Bulgaria',
            self::BF => 'Burkina Faso',
            self::BI => 'Burundi',
            self::KH => 'Cambodia',
            self::CM => 'Cameroon',
            self::CA => 'Canada',
            self::CV => 'Cape Verde',
            self::KY => 'Cayman Islands',
            self::CF => 'Central African Republic',
            self::TD => 'Chad',
            self::CL => 'Chile',
            self::CN => 'China',
            self::CX => 'Christmas Island',
            self::CC => 'Cocos (Keeling) Islands',
            self::CO => 'Colombia',
            self::KM => 'Comoros the',
            self::CD => 'Congo',
            self::CG => 'Congo the',
            self::CK => 'Cook Islands',
            self::CR => 'Costa Rica',
            self::CI => 'Cote d\'Ivoire',
            self::HR => 'Croatia',
            self::CU => 'Cuba',
            self::CY => 'Cyprus',
            self::CZ => 'Czech Republic',
            self::DK => 'Denmark',
            self::DJ => 'Djibouti',
            self::DM => 'Dominica',
            self::DO => 'Dominican Republic',
            self::EC => 'Ecuador',
            self::EG => 'Egypt',
            self::SV => 'El Salvador',
            self::GQ => 'Equatorial Guinea',
            self::ER => 'Eritrea',
            self::EE => 'Estonia',
            self::ET => 'Ethiopia',
            self::FO => 'Faroe Islands',
            self::FK => 'Falkland Islands (Malvinas)',
            self::FJ => 'Fiji the Fiji Islands',
            self::FI => 'Finland',
            self::FR => 'France, French Republic',
            self::GF => 'French Guiana',
            self::PF => 'French Polynesia',
            self::TF => 'French Southern Territories',
            self::GA => 'Gabon',
            self::GM => 'Gambia the',
            self::GE => 'Georgia',
            self::DE => 'Germany',
            self::GH => 'Ghana',
            self::GI => 'Gibraltar',
            self::GR => 'Greece',
            self::GL => 'Greenland',
            self::GD => 'Grenada',
            self::GP => 'Guadeloupe',
            self::GU => 'Guam',
            self::GT => 'Guatemala',
            self::GG => 'Guernsey',
            self::GN => 'Guinea',
            self::GW => 'Guinea-Bissau',
            self::GY => 'Guyana',
            self::HT => 'Haiti',
            self::HM => 'Heard Island and McDonald Islands',
            self::VA => 'Holy See (Vatican City State)',
            self::HN => 'Honduras',
            self::HK => 'Hong Kong',
            self::HU => 'Hungary',
            self::IS => 'Iceland',
            self::IN => 'India',
            self::ID => 'Indonesia',
            self::IR => 'Iran',
            self::IQ => 'Iraq',
            self::IE => 'Ireland',
            self::IM => 'Isle of Man',
            self::IL => 'Israel',
            self::IT => 'Italy',
            self::JM => 'Jamaica',
            self::JP => 'Japan',
            self::JE => 'Jersey',
            self::JO => 'Jordan',
            self::KZ => 'Kazakhstan',
            self::KE => 'Kenya',
            self::KI => 'Kiribati',
            self::KP => 'Korea',
            self::KR => 'Korea',
            self::KW => 'Kuwait',
            self::KG => 'Kyrgyz Republic',
            self::LA => 'Lao',
            self::LV => 'Latvia',
            self::LB => 'Lebanon',
            self::LS => 'Lesotho',
            self::LR => 'Liberia',
            self::LY => 'Libyan Arab Jamahiriya',
            self::LI => 'Liechtenstein',
            self::LT => 'Lithuania',
            self::LU => 'Luxembourg',
            self::MO => 'Macao',
            self::MK => 'Macedonia',
            self::MG => 'Madagascar',
            self::MW => 'Malawi',
            self::MY => 'Malaysia',
            self::MV => 'Maldives',
            self::ML => 'Mali',
            self::MT => 'Malta',
            self::MH => 'Marshall Islands',
            self::MQ => 'Martinique',
            self::MR => 'Mauritania',
            self::MU => 'Mauritius',
            self::YT => 'Mayotte',
            self::MX => 'Mexico',
            self::FM => 'Micronesia',
            self::MD => 'Moldova',
            self::MC => 'Monaco',
            self::MN => 'Mongolia',
            self::ME => 'Montenegro',
            self::MS => 'Montserrat',
            self::MA => 'Morocco',
            self::MZ => 'Mozambique',
            self::MM => 'Myanmar',
            self::NA => 'Namibia',
            self::NR => 'Nauru',
            self::NP => 'Nepal',
            self::AN => 'Netherlands Antilles',
            self::NL => 'Netherlands the',
            self::NC => 'New Caledonia',
            self::NZ => 'New Zealand',
            self::NI => 'Nicaragua',
            self::NE => 'Niger',
            self::NG => 'Nigeria',
            self::NU => 'Niue',
            self::NF => 'Norfolk Island',
            self::MP => 'Northern Mariana Islands',
            self::NO => 'Norway',
            self::OM => 'Oman',
            self::PK => 'Pakistan',
            self::PW => 'Palau',
            self::PS => 'Palestinian Territory',
            self::PA => 'Panama',
            self::PG => 'Papua New Guinea',
            self::PY => 'Paraguay',
            self::PE => 'Peru',
            self::PH => 'Philippines',
            self::PN => 'Pitcairn Islands',
            self::PL => 'Poland',
            self::PT => 'Portugal, Portuguese Republic',
            self::PR => 'Puerto Rico',
            self::QA => 'Qatar',
            self::RE => 'Reunion',
            self::RO => 'Romania',
            self::RU => 'Russian Federation',
            self::RW => 'Rwanda',
            self::BL => 'Saint Barthelemy',
            self::SH => 'Saint Helena',
            self::KN => 'Saint Kitts and Nevis',
            self::LC => 'Saint Lucia',
            self::MF => 'Saint Martin',
            self::PM => 'Saint Pierre and Miquelon',
            self::VC => 'Saint Vincent and the Grenadines',
            self::WS => 'Samoa',
            self::SM => 'San Marino',
            self::ST => 'Sao Tome and Principe',
            self::SA => 'Saudi Arabia',
            self::SN => 'Senegal',
            self::RS => 'Serbia',
            self::SC => 'Seychelles',
            self::SL => 'Sierra Leone',
            self::SG => 'Singapore',
            self::SK => 'Slovakia (Slovak Republic)',
            self::SI => 'Slovenia',
            self::SB => 'Solomon Islands',
            self::SO => 'Somalia, Somali Republic',
            self::ZA => 'South Africa',
            self::GS => 'South Georgia and the South Sandwich Islands',
            self::ES => 'Spain',
            self::LK => 'Sri Lanka',
            self::SD => 'Sudan',
            self::SR => 'Suriname',
            self::SJ => 'Svalbard & Jan Mayen Islands',
            self::SZ => 'Swaziland',
            self::SE => 'Sweden',
            self::CH => 'Switzerland, Swiss Confederation',
            self::SY => 'Syrian Arab Republic',
            self::TW => 'Taiwan',
            self::TJ => 'Tajikistan',
            self::TZ => 'Tanzania',
            self::TH => 'Thailand',
            self::TL => 'Timor-Leste',
            self::TG => 'Togo',
            self::TK => 'Tokelau',
            self::TO => 'Tonga',
            self::TT => 'Trinidad and Tobago',
            self::TN => 'Tunisia',
            self::TR => 'Turkey',
            self::TM => 'Turkmenistan',
            self::TC => 'Turks and Caicos Islands',
            self::TV => 'Tuvalu',
            self::UG => 'Uganda',
            self::UA => 'Ukraine',
            self::AE => 'United Arab Emirates',
            self::GB => 'United Kingdom',
            self::US => 'United States of America',
            self::UM => 'United States Minor Outlying Islands',
            self::VI => 'United States Virgin Islands',
            self::UY => 'Uruguay, Eastern Republic of',
            self::UZ => 'Uzbekistan',
            self::VU => 'Vanuatu',
            self::VE => 'Venezuela',
            self::VN => 'Vietnam',
            self::WF => 'Wallis and Futuna',
            self::EH => 'Western Sahara',
            self::YE => 'Yemen',
            self::ZM => 'Zambia',
            self::ZW => 'Zimbabwe',
        };
    }

    public function isEuropeanCountry(): bool
    {
        $europeanCountries = [
            self::AT, self::BE, self::BG, self::HR, self::CY, self::CZ, self::DK, self::EE, self::FI, self::FR,
            self::DE, self::GR, self::HU, self::IE, self::IT, self::LV, self::LT, self::LU, self::MT, self::NL,
            self::PL, self::PT, self::RO, self::SK, self::SI, self::ES, self::SE,
        ];

        return in_array($this, $europeanCountries);
    }
}
